version: "3.8"
services:
  api:
    image: tts-generator:v5
    ports:
      - "80:80" #localhost port : container exposed port
    working_dir: /app/api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
